
name: Build, release version and changelog and publish to NPM

on: [push]

jobs:

  build-test-release-and-publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
          registry-url: 'https://registry.npmjs.org'
          scope: '@igortrindade'
          always-auth: true
      - run: git config --global user.email "igortrindademe@gmail.com"
      - run: git config --global user.name "Igor Trindade"
      - run: pwd && npm ci
      - run: npm run test
      - run: npm run generate:types
      - run: npm run release
      - run: git push --follow-tags origin ${{ github.ref_name }}
      - run: npm publish --access public --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
